### ISSUE TITLE
Add support for CDK v2

### ISSUE THREAD

**Issue by brentryan** [k9securityio/k9-cdk#26]
CDK v2 has some breaking changes that need to be addressed and we'll likely want to have support for both v1 and v2 for some time.

https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html

**Comment by skuenzli** [comment]
Thanks for submitting the issue Brent!

Adapting to CDK v2 is on our roadmap, but we haven't given it a shot to see what breaks yet.

**Comment by brentryan** [comment]
You will likely need to support 2 long lived branches. They're not compatible with each other and we will need to support both until end of life of v1. We do this internally as well where we move to latest on main line and then keep a CDK v1 branch around.

We will need k9 support on v2 in order for us to use k9 in the new v2 branches we're building now internally. We might be able to contribute a pull request for this at some point as well.

**Comment by skuenzli** [comment]
Started this work on https://github.com/k9securityio/k9-cdk/tree/v2-main

No ETA on release yet.  CDKv2 requires more changes than we expected.

**Comment by skuenzli** [comment]
We have released k9-cdk 2.0.2+ for CDK v2!

You can find the binary releases on NPMJS: https://www.npmjs.com/package/@k9securityio/k9-cdk
