### ISSUE TITLE
"Error TS2307: Cannot find module 'aws-cdk-lib/aws-s3/lib/bucket' or its corresponding type declarations" when compiling a project with `moduleResolution: "node16"` 

### ISSUE THREAD

**Issue by ZachPerkins1** [k9securityio/k9-cdk#32]
This appears to be because of the following import:
https://github.com/k9securityio/k9-cdk/blob/4f8bd6b7fa7e891859e94970d628367c70a10b83/src/s3.ts#L11

Because of the node16 resolution rules, relative file imports in this case are not supported (unless accompanied by an extension).  
https://www.typescriptlang.org/docs/handbook/modules/reference.html#package-relative-file-paths 

The simple solution would be to replace this line with
`import { IBucket } from 'aws-cdk-lib/aws-s3';`
as this type is now exported from the root of aws-s3.

I made this modification locally within my own `node_modules` and it functioned as-expected. I can raise a PR for this, but wanted to just raise this first in case there's already been discussion or I am mistaken here.

**Comment by skuenzli** [comment]
Hi Zach - thanks for your patience! I didn't receive / see a notification for this.

Thanks for suggesting a fix. I will try it out.  FWIW, I have been developing w/ v20.14.0 (for a while).

**Comment by skuenzli** [comment]
@ZachPerkins1 - this issue is fixed in https://github.com/k9securityio/k9-cdk/commit/f7a527edd6e9a7247360adaeb13d70d4aa6abf26

Thanks for reporting it along with the solution!
